### ISSUE TITLE
Look into using adjacent selectors for grids

### ISSUE THREAD

**Issue by milesj** [titon/toolkit#108]
Instead of using margins and last child on a column, lets use adjacent columns, which are much simpler.

```css
.col + .col { margin-left: $gutter; }
```
