### ISSUE TITLE
responsive font-size

### ISSUE THREAD

**Issue by hsen-dev** [titon/toolkit#131]
How we can set different `font-size` in different devices (different display size)?

**Comment by milesj** [comment]
You would need to write media queries manually.

```scss
@media only screen and (max-width: 640px) {
    html { font-size: 10px; }
}
```
